[build]
functions = "src/functions"

[build.environment]
PYTHON_VERSION = "system"

[[redirects]]
from = "https://kalkspace.de/*"
to = "https://kalk.space/:splat"
status = 301
force = true

[[redirects]]
from = "/kegelbahn"
to = "https://bbb.kalk.space/rooms/gdf-1yc-88b-yxb/join"
status = 301
force = true

[[redirects]]
from = "/coc"
to = "https://discuss.kalk.space/t/code-of-conduct/262"
status = 301
force = true

[[redirects]]
from = "/events.ics"
to = "https://discuss.kalk.space/discourse-post-event/events.ics?order=desc"
status = 200
force = true

[[redirects]]
from = "/.well-known/matrix/*"
to = "https://matrix.kalk.space/.well-known/matrix/:splat"
status = 200
force = true

[[redirects]]
from = "/antrag"
to = "https://kalkspace.webling.ch/forms/memberform/3b2469ccc03be4f5a4d1"
status = 301
force = true
